version: "3.8"

services:
  zee-index:
    container_name: zee-index
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_ROOT_FOLDER_ID: ${NEXT_PUBLIC_ROOT_FOLDER_ID}
        NEXT_PUBLIC_ROOT_FOLDER_NAME: ${NEXT_PUBLIC_ROOT_FOLDER_NAME}
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
